# Generated by Django 5.1.5 on 2025-01-28 12:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_alter_destination_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='des',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
